services:
  attacker:
    image: handsonsecurity/seed-ubuntu:large
    container_name: seed-attacker
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    network_mode: host
    command: sleep infinity

  host:
    image: handsonsecurity/seed-ubuntu:large
    container_name: user-10.9.0.5
    tty: true
    cap_add:
      - ALL
    command: sleep infinity

    # no networks lets container use default bridge